//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bARBieEntities : DbContext
    {
        public bARBieEntities()
            : base("name=bARBieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BetFairCompetitionUrls> BetFairCompetitionUrls { get; set; }
        public DbSet<BetFairFootballOdds> BetFairFootballOdds { get; set; }
        public DbSet<Bookie> Bookie { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<FootballArbs> FootballArbs { get; set; }
        public DbSet<FootballCompetitions> FootballCompetitions { get; set; }
        public DbSet<FootballMatches> FootballMatches { get; set; }
        public DbSet<OddsCheckerCompetitionUrls> OddsCheckerCompetitionUrls { get; set; }
        public DbSet<OddsCheckerFootballOdds> OddsCheckerFootballOdds { get; set; }
        public DbSet<OddsCheckerFootballFixtures> OddsCheckerFootballFixtures { get; set; }
    }
}
