//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bARBieEntities : DbContext
    {
        public bARBieEntities()
            : base("name=bARBieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbs_Football_MatchWinner> Arbs_Football_MatchWinner { get; set; }
        public virtual DbSet<Arbs_Football_MatchWinner_Expired> Arbs_Football_MatchWinner_Expired { get; set; }
        public virtual DbSet<BetFairCompetitionUrls> BetFairCompetitionUrls { get; set; }
        public virtual DbSet<BetFairFootballFixtures> BetFairFootballFixtures { get; set; }
        public virtual DbSet<BetFairFootballOdds> BetFairFootballOdds { get; set; }
        public virtual DbSet<Bookie> Bookie { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<FootballCompetitions> FootballCompetitions { get; set; }
        public virtual DbSet<FootballFixturesMap> FootballFixturesMap { get; set; }
        public virtual DbSet<OddsCheckerCompetitionUrls> OddsCheckerCompetitionUrls { get; set; }
        public virtual DbSet<OddsCheckerFootballFixtures> OddsCheckerFootballFixtures { get; set; }
        public virtual DbSet<OddsCheckerFootballOdds> OddsCheckerFootballOdds { get; set; }
    }
}
