//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetFairFootballOdds
    {
        public int ID { get; set; }
        public System.DateTime MatchDateTime { get; set; }
        public string Fixture { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string Prediction { get; set; }
        public Nullable<decimal> BackLow { get; set; }
        public Nullable<decimal> BackLowCash { get; set; }
        public Nullable<decimal> BackMid { get; set; }
        public Nullable<decimal> BackMidCash { get; set; }
        public Nullable<decimal> BackHigh { get; set; }
        public Nullable<decimal> BackHighCash { get; set; }
        public Nullable<decimal> LayLow { get; set; }
        public Nullable<decimal> LayLowCash { get; set; }
        public Nullable<decimal> LayMid { get; set; }
        public Nullable<decimal> LayMidCash { get; set; }
        public Nullable<decimal> LayHigh { get; set; }
        public Nullable<decimal> LayHighCash { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
