//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.BetFairCompetitionUrls = new HashSet<BetFairCompetitionUrls>();
            this.BetFairFootballFixtures = new HashSet<BetFairFootballFixtures>();
            this.BetFairFootballOdds = new HashSet<BetFairFootballOdds>();
            this.OddsCheckerCompetitionUrls = new HashSet<OddsCheckerCompetitionUrls>();
            this.OddsCheckerFootballFixtures = new HashSet<OddsCheckerFootballFixtures>();
            this.OddsCheckerFootballOdds = new HashSet<OddsCheckerFootballOdds>();
        }
    
        public int ID { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<BetFairCompetitionUrls> BetFairCompetitionUrls { get; set; }
        public virtual ICollection<BetFairFootballFixtures> BetFairFootballFixtures { get; set; }
        public virtual ICollection<BetFairFootballOdds> BetFairFootballOdds { get; set; }
        public virtual ICollection<OddsCheckerCompetitionUrls> OddsCheckerCompetitionUrls { get; set; }
        public virtual ICollection<OddsCheckerFootballFixtures> OddsCheckerFootballFixtures { get; set; }
        public virtual ICollection<OddsCheckerFootballOdds> OddsCheckerFootballOdds { get; set; }
    }
}
