//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballCompetitions
    {
        public FootballCompetitions()
        {
            this.BetFairCompetitionUrls = new HashSet<BetFairCompetitionUrls>();
            this.OddsCheckerCompetitionUrls = new HashSet<OddsCheckerCompetitionUrls>();
            this.OddsCheckerFootballFixtures = new HashSet<OddsCheckerFootballFixtures>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Competition { get; set; }
    
        public virtual ICollection<BetFairCompetitionUrls> BetFairCompetitionUrls { get; set; }
        public virtual ICollection<OddsCheckerCompetitionUrls> OddsCheckerCompetitionUrls { get; set; }
        public virtual ICollection<OddsCheckerFootballFixtures> OddsCheckerFootballFixtures { get; set; }
    }
}
