//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballFixturesMap
    {
        public int ID { get; set; }
        public int BetFairFixtureID { get; set; }
        public int OddsCheckerFixtureID { get; set; }
    
        public virtual FootballCompetitions FootballCompetitions { get; set; }
        public virtual FootballCompetitions FootballCompetitions1 { get; set; }
    }
}
