//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbieMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bARBieEntities : DbContext
    {
        public bARBieEntities()
            : base("name=bARBieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arbs_Football_MatchWinner> Arbs_Football_MatchWinner { get; set; }
        public DbSet<BetFairCompetitionUrl> BetFairCompetitionUrls { get; set; }
        public DbSet<BetFairFootballFixture> BetFairFootballFixtures { get; set; }
        public DbSet<BetFairFootballOdd> BetFairFootballOdds { get; set; }
        public DbSet<Bookie> Bookies { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<FootballCompetition> FootballCompetitions { get; set; }
        public DbSet<FootballFixturesMap> FootballFixturesMaps { get; set; }
        public DbSet<OddsCheckerCompetitionUrl> OddsCheckerCompetitionUrls { get; set; }
        public DbSet<OddsCheckerFootballFixture> OddsCheckerFootballFixtures { get; set; }
        public DbSet<OddsCheckerFootballOdd> OddsCheckerFootballOdds { get; set; }
    }
}
