//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbieMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetFairFootballFixture
    {
        public BetFairFootballFixture()
        {
            this.BetFairFootballOdds = new HashSet<BetFairFootballOdd>();
            this.FootballFixturesMaps = new HashSet<FootballFixturesMap>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int CompetitionID { get; set; }
        public System.DateTime MatchDateTime { get; set; }
        public string HomeTeam { get; set; }
        public string AwayTeam { get; set; }
        public string MatchWinnerOddsUrl { get; set; }
    
        public virtual FootballCompetition FootballCompetition { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<BetFairFootballOdd> BetFairFootballOdds { get; set; }
        public virtual ICollection<FootballFixturesMap> FootballFixturesMaps { get; set; }
    }
}
