//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbieMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FootballCompetition
    {
        public FootballCompetition()
        {
            this.BetFairCompetitionUrls = new HashSet<BetFairCompetitionUrl>();
            this.BetFairFootballFixtures = new HashSet<BetFairFootballFixture>();
            this.BetFairFootballOdds = new HashSet<BetFairFootballOdd>();
            this.OddsCheckerCompetitionUrls = new HashSet<OddsCheckerCompetitionUrl>();
            this.OddsCheckerFootballFixtures = new HashSet<OddsCheckerFootballFixture>();
            this.OddsCheckerFootballOdds = new HashSet<OddsCheckerFootballOdd>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Competition { get; set; }
    
        public virtual ICollection<BetFairCompetitionUrl> BetFairCompetitionUrls { get; set; }
        public virtual ICollection<BetFairFootballFixture> BetFairFootballFixtures { get; set; }
        public virtual ICollection<BetFairFootballOdd> BetFairFootballOdds { get; set; }
        public virtual ICollection<OddsCheckerCompetitionUrl> OddsCheckerCompetitionUrls { get; set; }
        public virtual ICollection<OddsCheckerFootballFixture> OddsCheckerFootballFixtures { get; set; }
        public virtual ICollection<OddsCheckerFootballOdd> OddsCheckerFootballOdds { get; set; }
    }
}
