//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarbieMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OddsCheckerFootballOdd
    {
        public int ID { get; set; }
        public int FixtureID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int CompetitionID { get; set; }
        public string Prediction { get; set; }
        public Nullable<decimal> Bet365 { get; set; }
        public Nullable<decimal> SkyBet { get; set; }
        public Nullable<decimal> ToteSport { get; set; }
        public Nullable<decimal> BoyleSports { get; set; }
        public Nullable<decimal> BetFred { get; set; }
        public Nullable<decimal> SportingBet { get; set; }
        public Nullable<decimal> BetVictor { get; set; }
        public Nullable<decimal> PaddyPower { get; set; }
        public Nullable<decimal> StanJames { get; set; }
        public Nullable<decimal> C888Sport { get; set; }
        public Nullable<decimal> Ladbrokes { get; set; }
        public Nullable<decimal> Coral { get; set; }
        public Nullable<decimal> WilliamHill { get; set; }
        public Nullable<decimal> Winner { get; set; }
        public Nullable<decimal> SpreadEx { get; set; }
        public Nullable<decimal> BetWay { get; set; }
        public Nullable<decimal> Bwin { get; set; }
        public Nullable<decimal> UniBet { get; set; }
        public Nullable<decimal> YouWin { get; set; }
        public Nullable<decimal> C32RedBet { get; set; }
        public Nullable<decimal> BetFair { get; set; }
        public Nullable<decimal> BetDaq { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual FootballCompetition FootballCompetition { get; set; }
        public virtual OddsCheckerFootballFixture OddsCheckerFootballFixture { get; set; }
    }
}
